#pragma once

#include "lvgl.h"

/*
 * Chinese fonts: Alibaba PuHui (basic set, ~3500 common CJK + ASCII)
 * Icon font: Font Awesome 6 (symbols, emoji alternatives, status icons)
 *
 * Generated by lv_font_conv from xiaozhi-fonts component.
 */

/* CJK + ASCII text fonts */
LV_FONT_DECLARE(font_puhui_basic_14_1);
LV_FONT_DECLARE(font_puhui_basic_20_4);
LV_FONT_DECLARE(font_puhui_basic_30_4);

/* Font Awesome icon font */
LV_FONT_DECLARE(font_awesome_20_4);
